### PR TITLE
[MIRROR]: Adds in a new type of securitron

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
Original Author: Kmc2000
Original PR Link: https://github.com/tgstation/tgstation/pull/39382

:cl: Kmc2000
add: You can now attach 4 energy swords to a securiton assembly instead of a baton to create a 4 esword wielding nightmare-bot
/:cl:

Meet General Beepsky!
He's Officer Beepsky's more robust cousin, instead of stunning and arresting people, he'll only stop when they're dead!
This bot will mercilessly track, kill, maim and subsequently disembowel his victims.

https://i.gyazo.com/6e5be23a4a9356551bc338ec22d88653.mp4

An emagged general beepsky:
https://i.gyazo.com/f173f33ba537881cd2ceaad1dd531e86.mp4

Try emagging him for even more fun!

He's pretty robust because of the exhorbitant materials cost for making him, and will likely only be used on meme filled nukeop rounds or for adminbus purposes

To create one, follow the securitron assembly instructions all the way up to attaching his baton, instead attach 4 eswords and security's murderous new mascot will be complete!

### CODE REVIEW

**Comment by CthulhuOnIce** [comment]
This was a PR mirror test. Do not Merge.

**Comment by Kmc2000** [comment]
>do not merge

This feature

Are you mad

**Comment by CthulhuOnIce** [comment]
Pfft, it's just a test, the branch it's merging from is actually my own, and only adds a hub message, the script only grabbed the title and body of yours.

When i figure out what to put in the head field, so it actually uses your own fork, i will merge this.

**Comment by Kmc2000** [comment]
:^))))

**Pull request merged**
